### ISSUE TITLE
excessive detection time

### ISSUE THREAD

**Issue by mcl-uk** [tonytw1/squirrel-detector#6]
Hello & thanks for sharing this brilliant project.
You talk about detection times, on a regular CPU, in the order of 99ms.
When I run your check.py code (w/ mostly-fox.jpg) on my 13th gen i5 the detection line takes ~1s to execute!
I have no GPU.
Am I doing something wrong?
Thanks for your help.

**Comment by tonytw1** [comment]
Hi @mcl-uk 

Pardon for not seeing this earlier.
It appears you are correct! The first detection made by a newly loaded copy of the model really is taking ~ 800ms.

In #7 I've changed `check.py` to take several images as input and logged the time each step is taking.
The first detection is slow; the 2nd and 3rd detections fall back down to the ~ 40-50ms range I was expecting.

Interesting. 
TensorFlow must be caching parts of the model or benefiting from some other sort of warmup.
I've not noticed this because I'm using the model inside a long running message listener which reuses the loaded model many times.

The CPU which produced these timings is a v4 Intel:
`Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz`

**Comment by mcl-uk** [comment]
Thanks again, very helpful. FYI also found this (https://github.com/rb2k/sqwrlmodel) tflite model that works really fast too.
